# Generated by Django 3.0.3 on 2020-02-21 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0002_auto_20200220_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet_like_owner', to=settings.AUTH_USER_MODEL)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets_liked', to='tweet.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_liked', to='tweet.Comment')),
                ('like_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_like_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
