# Generated by Django 3.0.3 on 2020-02-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_commentlike_tweetlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='like_owner',
            new_name='comment_like_owner',
        ),
        migrations.RenameField(
            model_name='tweetlike',
            old_name='like_owner',
            new_name='tweet_like_owner',
        ),
    ]
